In [1]:
import numpy as np

### Make a Numpy Array

In [2]:
arr=np.array([23,1,4,5,1])
print(arr)

[23  1  4  5  1]


### Numpy vs List https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC

In [3]:
import time

In [4]:
size=100_000_000
start=time.time()
py_list=list(range(size))
sq=[x**2 for x in py_list]
end=time.time()
print("Pyhton List time : ",end-start)

start=time.time()
num_array=np.array(py_list)
sq_np=num_array ** 2
end=time.time()
print("Numpy list time : ",end-start)

Pyhton List time :  26.675630569458008
Numpy list time :  15.552192687988281


### 2D array creating
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
#### Use of shape(check dimensions Of Array) ,dtype(use for checking type of data in an array)

In [5]:
arr2d=np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(arr2d)
print(arr2d.shape,arr2d.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) int64


### Creating array using built in methods
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
### zeros,ones,full,eye,arange(start,end,step),linspace(start,end,evenly spaced values)

In [22]:
arrzeros=np.zeros((2,3), dtype="int64")
print(arrzeros)

arrones=np.ones((3,3))#prefill
print(arrones)

arrfull=np.full((2, 3), 9)     # 2D array, sab 9 full
print(arrfull)

arr_eye=np.eye((3),dtype="int64") # identity matrix
print(arr_eye)

arr_arrange=np.arange(1,10,2)
print(arr_arrange)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 3 5 7 9]


### Arrays Properties(6)
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
### dtype,shape,size,ndim,astype


In [30]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2.dtype)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

float_Array=arr2.astype(np.float64)
print(float_Array)

int64
(3, 3)
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Reshaping an numpy array(7)
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
### arrayname.reshape(use for reshaping an array eg:convert 2*3, into 3*2),arrayname.flatten(convert 2d array into a 1d array)


In [34]:
arr3=np.array([
    [1,2,3],
    [4,5,6]
])
reshaping=arr3.reshape((3,2))
print(reshaping)

print(arr3.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### Indexing(8)
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
### indexing by index,fancy indexing,bolean indexing

In [46]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[0][2]) #(give index number in row and column wise)

idx=[0,1]
print(arr[idx]) #fancy indexing

bolean_indexing=(arr%2==0) #Bolean indexing
print(bolean_indexing)


3
[[1 2 3]
 [4 5 6]]
[[False  True False]
 [ True False  True]]


### slicing(9)
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
### slicing in an nparray

In [53]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[0:1])

print(arr[0:1, 1:2])  # row 0, column 1

[[1 2 3]]
[[2]]


###  Copy vs view(10)
### https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
# in simple python list copy created,in numpy array a view created in memory


In [58]:
arr=[1,2,3,4,5,6]
sub_array=arr[1:3]
print(arr)
print(sub_array)
sub_array[0]=200
print(sub_array)


arrnp=np.array([1,2,3,4,5,6])
sub_array_np=arrnp[1:3]
print(arrnp)
print(sub_array_np)
sub_array_np[0]=200
print(sub_array_np)
print(arrnp)

[1, 2, 3, 4, 5, 6]
[2, 3]
[200, 3]
[1 2 3 4 5 6]
[2 3]
[200   3]
[  1 200   3   4   5   6]


***

### Common Data Types in Numpy https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC
- Integers: int32, int64
- Floating point nums: float32, float64
- Boolean: bool
- Complex nums: complex64, complex128
- String: S (byte-str) & U (unicode-str)
- Object: generic python objects - object

In [59]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


***
### 3D ARRAY(13)
- link https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC


In [61]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d[0,0,1])

2


***

### Vectorization & Broadcasting(14)
- link https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC

<b>1. Vectorization</b>: It is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops. 

<b>2. Broadcasting</b>: It is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them (creating copies of the smaller array to match the larger array's shape). 

<b> Broadcasting Condition <b>

For broadcasting to happen the dimensions should be compatible. Numpy compares shape element-wise. It starts dimension comparison with the trailing (i.e. rightmost) dimension and works its way left. 
Two dimensions are compatible when <ol> <li>they are equal, or</li> <li>one of them is 1. </li>

In [62]:
# Vectorization & Broadcasting

#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


# Vector Normalization(15)
- link https://drive.google.com/drive/folders/1MAiVA2sXVel7Obkj7HMzFke5zDg7b0KC

In [63]:
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

print((arr - mean) / std_dev)

#column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


***

### Mathematical Functions in NumPy
There are lots of important & commonly used mathematical functions in NumPy.
1. Aggregation functions
   - sum()
   - prod()
   - min() & argmin() - min val & idx of min val
   - max() & argmax() - max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [65]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


2. Power functions
   - square()
   - sqrt() - square root
   - pow(a, b) - a^b

In [66]:
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


3. Log & Exponential functions
   - log() - natual log
   - log10() - log base 10
   - log2() - log base 2
   - exp() - exponentional i.e. e^x

In [67]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


4. Rounding functions
   - round() - rounds to nearest value
   - floor() - rounds down
   - ceil() - rounds up
   - trunc() - truncates decimal part

In [70]:
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0
print(np.unique(arr))
print(np.sort(arr))

3.0
2.0
3.0
2.0
[1 2 3 4 5]
[1 2 3 4 5]
